-ignorewarnings
-verbose

-keep class org.lwjgl.** { *; }
-keep class org.bouncycastle.** { *; }
-keep class com.android.apksig.** { *; }
-keep class org.sqlite.** { *; }
-keep class org.slf4j.** { *; }
-keep class com.sun.jna.** { *; }
-keep class java.nio.** { *; }
-keep class java.util.concurrent.** { *; }
-keep class uniffi.toolkit.** { *; }
-keepattributes Signature,LineNumberTable,RuntimeVisibleAnnotations,AnnotationDefault,*Annotation*,InnerClasses