[package]
name = "toolkit-rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "toolkit_rs"

[dependencies]
uniffi = "0.27.3"
image = "0.25.1"
imagequant = "4.3.1"
thiserror = "1.0.61"
lodepng = "3.10.1"
fast_image_resize = { version = "4.0.0", features = ["image"] }
mozjpeg = "0.10.7"
oxipng = { version = "9.0", features = ["parallel", "zopfli", "filetime"], default-features = false }

[build-dependencies]
uniffi = { version = "0.27.3", features = ["build"] }

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"
