import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.jetbrainsCompose)
    alias(libs.plugins.githubBuildconfig)
    alias(libs.plugins.kotlinSerialization)
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.about.libraries)
    alias(libs.plugins.koin.compiler)
}

// Build properties
val kitVersion: String by project
val kitPackageName: String by project
val kitDescription: String by project
val kitCopyright: String by project
val kitVendor: String by project
val kitLicenseFile: String by project

// Rust configuration
val linuxArmTarget = "aarch64-unknown-linux-gnu"
val linuxX64Target = "x86_64-unknown-linux-gnu"
val useCross = (properties.getOrDefault("useCross", "false") as String).toBoolean()
val isLinuxAarch64 = (properties.getOrDefault("isLinuxAarch64", "false") as String).toBoolean()

// Generated source paths
val rustGeneratedSource =
    "${layout.buildDirectory.get()}/generated/source/uniffi/main/org/tool/kit/kotlin"
val aboutLibrariesSource = "src/commonMain/composeResources/files/aboutlibraries.json"

// Rust compilation and binding generation run during task execution.
val rustProject = rootProject.layout.projectDirectory.dir("rust")
val rustTarget = if (currentOs() == OS.LINUX && useCross) {
    if (isLinuxAarch64) linuxArmTarget else linuxX64Target
} else null
val rustReleaseDir = rustProject.dir("target/${rustTarget?.let { "$it/" } ?: ""}release")
val rustLibraryName = when (currentOs()) {
    OS.LINUX -> "libtoolkit_rs.so"
    OS.WINDOWS -> "toolkit_rs.dll"
    OS.MAC -> "libtoolkit_rs.dylib"
}
val packagedRustLibraryName = when (currentOs()) {
    OS.LINUX -> "libuniffi_toolkit.so"
    OS.WINDOWS -> "uniffi_toolkit.dll"
    OS.MAC -> "libuniffi_toolkit.dylib"
}
val rustInputs = fileTree(rustProject) {
    include("Cargo.toml", "Cargo.lock", "build.rs", "uniffi-bindgen.rs", "src/**", ".cargo/**")
    exclude("src/lut.inc") // Generated by build.rs; it must not invalidate its own task.
}
// GUI-launched IDEs may omit Rust/Homebrew from PATH. Resolve executables only when
// a Rust task runs, so project sync does not require an installed Rust toolchain.
val rustToolDirectories = buildList {
    addAll(providers.environmentVariable("PATH").getOrElse("").split(File.pathSeparator).filter(String::isNotBlank))
    providers.environmentVariable("CARGO_HOME").orNull?.let { add(File(it, "bin").path) }
    add(File(System.getProperty("user.home"), ".cargo/bin").path)
    if (currentOs() == OS.MAC) addAll(listOf("/opt/homebrew/bin", "/usr/local/bin"))
}.distinct()

fun rustExecutable(tool: String): File {
    val configuredPath = providers.gradleProperty("${tool}Executable").orNull
    val name = if (currentOs() == OS.WINDOWS) "$tool.exe" else tool
    val candidates = if (configuredPath != null) listOf(rootProject.file(configuredPath))
        else rustToolDirectories.map { File(it, name) }
    return candidates.firstOrNull { it.isFile && it.canExecute() }
        ?: throw GradleException(
            "Cannot find executable $tool. Install the Rust toolchain or set " +
                "-P${tool}Executable=/absolute/path/to/$name. Checked: " + candidates.joinToString { it.path }
        )
}

fun Exec.configureRustExecutable(tool: String) {
    val cargo = rustExecutable("cargo")
    val command = if (tool == "cargo") cargo else rustExecutable(tool)
    executable(command.absolutePath)
    // Cargo/cross also launch rustc and other tools; resolving cargo alone is insufficient.
    environment("PATH", (listOf(cargo.parent, command.parent) + rustToolDirectories)
        .distinct().joinToString(File.pathSeparator))
}

val buildRustLibrary = tasks.register<Exec>("buildRustLibrary") {
    group = "build"
    description = "Build the native library for the selected desktop platform."
    workingDir(rustProject)
    commandLine(buildList {
        add(if (currentOs() == OS.LINUX && useCross) "cross" else "cargo")
        addAll(listOf("build", "--release", "--features=uniffi/cli"))
        rustTarget?.let { add("--target=$it") }
    })
    doFirst { configureRustExecutable(if (currentOs() == OS.LINUX && useCross) "cross" else "cargo") }
    inputs.files(rustInputs)
    inputs.property("target", rustTarget ?: "host-${System.getProperty("os.arch")}")
    inputs.property("os", currentOs().name)
    // Cargo owns incremental native compilation and toolchain/environment tracking.
    outputs.file(rustReleaseDir.file(rustLibraryName))
    outputs.upToDateWhen { false }
}
val generateRustBindings = tasks.register<Exec>("generateRustBindings") {
    group = "build"
    description = "Generate UniFFI Kotlin sources before JVM compilation."
    dependsOn(buildRustLibrary)
    workingDir(rustProject)
    commandLine("cargo", "run", "--features=uniffi/cli", "--bin", "uniffi-bindgen",
        "generate", "src/toolkit.udl", "--language", "kotlin", "--out-dir", rustGeneratedSource)
    doFirst { configureRustExecutable("cargo") }
    inputs.files(rustInputs)
    outputs.dir(rustGeneratedSource)
}
val copyRustLibrary = tasks.register<Sync>("copyRustLibrary") {
    group = "build"
    description = "Package the native library at the classpath root expected by UniFFI."
    dependsOn(buildRustLibrary)
    from(rustReleaseDir.file(rustLibraryName)) { rename { packagedRustLibraryName } }
    into(layout.buildDirectory.dir("generated/rustResources"))
}
tasks.register("rustTasks") {
    group = "build"
    description = "Prepare desktop UniFFI bindings and native resources."
    dependsOn(generateRustBindings, copyRustLibrary)
}

val javaLanguageVersion = JavaLanguageVersion.of(21)

// Group and version
group = "org.tool.kit"
version = kitVersion

kotlin {
    // Java toolchain
    jvmToolchain {
        languageVersion.set(javaLanguageVersion)
    }

    // Target configuration
    jvm()

    // Source sets
    sourceSets {
        // Add Rust generated source to JVM
        jvmMain.get().kotlin.srcDir(generateRustBindings)
        jvmMain.get().resources.srcDir(copyRustLibrary)

        // Common dependencies
        commonMain.dependencies {
            implementation(project.dependencies.platform(libs.koin.bom))
            implementation(libs.koin.core)
            implementation(libs.koin.compose)
            implementation(libs.koin.compose.viewmodel)
            implementation(libs.lifecycle.runtime.compose)
            implementation(libs.kotlinx.coroutines.core)
            // Compose dependencies (API for downstream modules)
            api(libs.compose.runtime)
            api(libs.compose.runtime.saveable)
            api(libs.compose.ui)
            api(libs.compose.foundation)
            api(libs.compose.material)
            api(libs.compose.material3)
            api(libs.compose.components.resources)
            api(libs.compose.material.icons.extended.desktop)
            api(libs.compose.navigation3.ui)
            api(libs.compose.adaptive)
            api(libs.compose.adaptive.navigation3)
            api(libs.compose.savedstate.compose)

            // Lifecycle
            implementation(libs.lifecycle.viewmodel.compose)
            implementation(libs.lifecycle.viewmodel.navigation3)

            // Kotlin libraries
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.kotlinx.datetime)

            // Settings
            implementation(libs.multiplatform.settings)
            implementation(libs.multiplatform.settings.coroutines)
            implementation(libs.multiplatform.settings.serialization)

            // Image handling
            implementation(libs.coil.compose)
            implementation(libs.zoomimage.compose.coil3)

            // UI components
            implementation(libs.markdown.renderer.jvm)
            implementation(libs.markdown.renderer.m3)
            implementation(libs.compottie)
            implementation(libs.compottie.dot)
            implementation(libs.compottie.resources)

            // About libraries
            implementation(libs.about.libraries.core)
            implementation(libs.about.libraries.compose.m3)

        }

        // JVM-specific dependencies
        jvmMain.dependencies {
            // Logging is a deliberate JVM API because composeApp imports KotlinLogging.
            api(libs.logging)
            implementation(libs.slf4j.api)
            implementation(libs.logback.core)
            implementation(libs.logback.classic)
            implementation(libs.filekit.core)
            implementation(libs.filekit.dialogs)
            implementation(libs.filekit.dialogs.compose)
            // IntelliJ utilities (with extensive exclusions)
            implementation("com.jetbrains.intellij.platform:util:253.29346.308") {
                exclude(group = "com.fasterxml", module = "aalto-xml")
                exclude(group = "com.github.ben-manes.caffeine", module = "caffeine")
                exclude(group = "com.intellij.platform", module = "kotlinx-coroutines-core-jvm")
                exclude(group = "com.intellij.platform", module = "kotlinx-coroutines-debug")
                exclude(group = "com.jetbrains.intellij.platform", module = "util-jdom")
                exclude(group = "com.jetbrains.intellij.platform", module = "util-class-loader")
                exclude(group = "com.jetbrains.intellij.platform", module = "util-xml-dom")
                exclude(group = "commons-codec", module = "commons-codec")
                exclude(group = "commons-io", module = "commons-io")
                exclude(group = "net.java.dev.jna", module = "jna-platform")
                exclude(group = "org.apache.commons", module = "commons-compress")
                exclude(
                    group = "org.jetbrains.intellij.deps.fastutil",
                    module = "intellij-deps-fastutil"
                )
                exclude(group = "org.jetbrains.kotlin", module = "kotlin-stdlib")
                exclude(group = "org.jetbrains.kotlinx", module = "kotlinx-serialization-core-jvm")
                exclude(group = "org.jetbrains.kotlinx", module = "kotlinx-serialization-json-jvm")
                exclude(group = "org.lz4", module = "lz4-java")
                exclude(group = "org.slf4j", module = "log4j-over-slf4j")
                exclude(group = "oro", module = "oro")
            }

            // HTTP transport (including Apache5) stays behind UpdateRepository.
            implementation(libs.ktor.client.core)
            implementation(libs.ktor.client.cio)
            implementation(libs.ktor.client.apache5)
            implementation(libs.ktor.client.logging)
            implementation(libs.ktor.client.content.negotiation)
            implementation(libs.ktor.serialization.kotlinx.json)

            // UniFFI generated sources and JNA are desktop implementation details.
            implementation(libs.jna)
            // APK parsing, signing, templates and bundled JVM jars.
            implementation(libs.android.apksig)
            implementation(libs.android.sdk.common)
            implementation(libs.google.guava)
            implementation(libs.android.binary.resources)
            implementation(libs.android.apkanalyzer.get().copy()) {
                // Apktool supplies its Smali fork under the same com.android.tools.smali packages.
                // Keep that complete set; Google's artifacts duplicate classes in the release JAR.
                exclude(group = "com.android.tools.smali")
            }
            implementation(libs.android.zipflinger)
            implementation(fileTree(mapOf("dir" to "libs", "include" to listOf("*.jar"))))
            implementation(libs.commons.codec)
            implementation(libs.apktool.lib)

            implementation(libs.asm)
            implementation(compose.desktop.currentOs)
            implementation(libs.kotlinx.coroutines.core)
            implementation(libs.kotlinx.coroutines.swing)
        }

        commonTest.dependencies {
            implementation(project.dependencies.platform(libs.koin.bom))
            implementation(libs.koin.test)
            implementation(libs.kotlin.test)
            implementation(libs.kotlinx.coroutines.test)
            implementation(libs.multiplatform.settings.test)
        }
        jvmTest.dependencies {
            implementation(libs.kotlin.test.junit)
            implementation(libs.junit)
            implementation(libs.compose.ui.test)
        }
    }
}

// Kotlin compiler options
tasks.withType<KotlinCompile>().configureEach {
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_21)
        freeCompilerArgs.add("-opt-in=kotlin.RequiresOptIn")
    }
}

// Compile the Domain closure independently: no application output, Compose,
// Koin, FileKit, JVM tool jars, or serialization compiler plugin is on this path.
val domainBoundaryLibraries = configurations.create("domainBoundaryLibraries") {
    isCanBeConsumed = false
    isCanBeResolved = true
    attributes {
        attribute(Usage.USAGE_ATTRIBUTE, objects.named(Usage.JAVA_API))
        attribute(org.jetbrains.kotlin.gradle.plugin.KotlinPlatformType.attribute,
            org.jetbrains.kotlin.gradle.plugin.KotlinPlatformType.jvm)
    }
}
dependencies {
    add(domainBoundaryLibraries.name, "org.jetbrains.kotlin:kotlin-stdlib:${libs.versions.kotlin.get()}")
    add(domainBoundaryLibraries.name, libs.kotlinx.coroutines.core)
    add(domainBoundaryLibraries.name, libs.kotlinx.serialization.json)
}
val domainBoundarySources = fileTree("src/commonMain/kotlin") {
    include("org/tool/kit/domain/**/*.kt", "org/tool/kit/model/UserData.kt", "org/tool/kit/model/IconFactoryData.kt")
}
val compileDomainBoundary = tasks.register<JavaExec>("compileDomainBoundary") {
    group = "verification"
    description = "Compile Domain and its value models without Compose, DI or platform implementations."
    // Invoke the existing compiler directly so no application compiler plugins are inherited.
    classpath(configurations.named("kotlinCompilerClasspath"))
    mainClass.set("org.jetbrains.kotlin.cli.jvm.K2JVMCompiler")
    javaLauncher.set(javaToolchains.launcherFor { languageVersion.set(javaLanguageVersion) })
    val destination = layout.buildDirectory.dir("architecture/domain-classes")
    val classpathReport = layout.buildDirectory.file("architecture/domain-classpath.txt")
    inputs.files(domainBoundarySources, domainBoundaryLibraries)
    outputs.dir(destination)
    outputs.file(classpathReport)
    doFirst {
        destination.get().asFile.deleteRecursively()
        destination.get().asFile.mkdirs()
        setArgs(listOf("-no-stdlib", "-no-reflect", "-jvm-target", "21", "-classpath", domainBoundaryLibraries.asPath,
            "-d", destination.get().asFile.absolutePath) + domainBoundarySources.files.sortedBy { it.path }.map { it.absolutePath })
    }
    doLast {
        classpathReport.get().asFile.writeText(domainBoundaryLibraries.files.sortedBy { it.name }
            .joinToString("\n") { it.absolutePath } + "\n")
    }
}
tasks.named("check") { dependsOn(compileDomainBoundary) }

// About Libraries configuration
aboutLibraries {
    export {
        outputFile = file(aboutLibrariesSource)
    }
}

// BuildConfig generation
buildConfig {
    className("BuildConfig")
    packageName("org.tool.kit")
    buildConfigField("APP_NAME", kitPackageName)
    buildConfigField("APP_VERSION", kitVersion)
    buildConfigField("APP_DESCRIPTION", kitDescription)
    buildConfigField("APP_COPYRIGHT", kitCopyright)
    buildConfigField("APP_VENDOR", kitVendor)
    buildConfigField("APP_LICENSE", "MIT License")
    buildConfigField("APP_LICENSE_URI", uri("https://opensource.org/license/mit"))
    buildConfigField("APP_LICENSE_FILE", rootProject.file(kitLicenseFile))
    buildConfigField("AUTHOR_GITHUB_URI", uri("https://github.com/LazyIonEs"))
    buildConfigField("APP_GITHUB_URI", uri("https://github.com/LazyIonEs/AndroidToolKit"))
}

// ========================================
// Rust Integration Configuration
// ========================================

/**
 * Operating system enumeration
 */
enum class OS {
    LINUX,
    WINDOWS,
    MAC
}

/**
 * Determine current operating system
 */
fun currentOs(): OS {
    val os = System.getProperty("os.name")
    return when {
        os.equals("Mac OS X", ignoreCase = true) -> OS.MAC
        os.startsWith("Win", ignoreCase = true) -> OS.WINDOWS
        os.startsWith("Linux", ignoreCase = true) -> OS.LINUX
        else -> error("Unknown OS name: $os")
    }
}

// Export library definitions for aboutlibraries
tasks.getByName("copyNonXmlValueResourcesForCommonMain").dependsOn("exportLibraryDefinitions")

tasks.withType<Test>().configureEach {
    systemProperty("java.util.prefs.PreferencesFactory", "org.tool.kit.tests.support.IsolatedPreferencesFactory")
    systemProperty("test.apkTemplate", rootProject.file("composeApp/resources/common/apktool.apk").absolutePath)
    systemProperty("test.fixtureRoot", layout.buildDirectory.dir("test-fixtures").get().asFile.absolutePath)
    systemProperty("user.language", "zh")
    systemProperty("user.country", "CN")
}
